[tool.poetry]
name = "churchsuite"
version = "0.1.0"
description = "A Python package for consuming the ChurchSuite API"
authors = ["St Mary's Church, Whitkirk <tech@whitkirkchurch.org.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10.5"
pytz = "^2022.2"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
freezegun = "^1.2.2"
coverage = "^6.4.4"
requests-mock = "^1.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
